# Generated by Django 3.2.12 on 2023-02-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=255)),
                ('comp_email', models.CharField(max_length=255)),
                ('ID', models.CharField(max_length=255)),
                ('Telephone_no', models.IntegerField(max_length=255)),
                ('estd_year', models.DateField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
