# Generated by Django 3.2.12 on 2023-02-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('salary', models.IntegerField(max_length=255)),
                ('Exp', models.CharField(max_length=255)),
                ('Requirnments', models.CharField(max_length=255)),
            ],
        ),
    ]
