# Generated by Django 4.1.5 on 2023-02-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(max_length=10),
        ),
    ]
